CREATE TABLE job_info (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    job_name VARCHAR(31) NOT NULL COMMENT '任务名称',
    job_code VARCHAR(31) NOT NULL COMMENT '任务编码',
    remark VARCHAR(255) COMMENT '任务描述',
    job_type TINYINT NOT NULL DEFAULT 0 COMMENT '任务类型',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB COMMENT='任务信息表';